/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyRatingsRouteImport } from './routes/my-ratings'
import { Route as IndexRouteImport } from './routes/index'

const MyRatingsRoute = MyRatingsRouteImport.update({
  id: '/my-ratings',
  path: '/my-ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-ratings': typeof MyRatingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-ratings': typeof MyRatingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-ratings': typeof MyRatingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-ratings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-ratings'
  id: '__root__' | '/' | '/my-ratings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyRatingsRoute: typeof MyRatingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-ratings': {
      id: '/my-ratings'
      path: '/my-ratings'
      fullPath: '/my-ratings'
      preLoaderRoute: typeof MyRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyRatingsRoute: MyRatingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
