from typing import Any, Generic, Protocol, TypeVar

from django.db.models import Model

T = TypeVar("T", bound=Model)


class IRepository(Protocol, Generic[T]):
    def get_all(self) -> list[T]: ...

    def get_by_id(self, id: str) -> T: ...

    def get_by_field(self, field_name: str, value: Any) -> T: ...

    def filter(self, *args: Any, **kwargs: Any) -> list[T]: ...

    def get_or_create(self, **kwargs: Any) -> tuple[T, bool]: ...

    def update(self, obj: T, **kwargs: Any) -> T: ...

    def delete(self, obj: T) -> bool: ...
