from typing import Any, Protocol, TypeVar

T = TypeVar("T")


class IRepository(Protocol[T]):
    def get_all(self) -> list[T]: ...

    def get_by_id(self, id: str) -> T: ...

    def filter(self, *args: Any, **kwargs: Any) -> Any: ...

    def get_or_create(self, **kwargs: Any) -> tuple[T, bool]: ...

    def update(self, obj: T, **kwargs: Any) -> T: ...

    def delete(self, obj: T) -> None: ...
