# Generated by Django 5.2.3 on 2025-10-03 08:47

import django.core.validators
import rating_app.models.course
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("faculty", models.CharField(max_length=255)),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1991,
                                message="Year cannot be earlier than 1991 (NaUKMA foundation)",
                            ),
                            rating_app.models.course.year_format_validator,
                        ]
                    ),
                ),
                ("ukma_id", models.CharField(max_length=6, unique=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
    ]
