# Generated by Django 5.2.3 on 2025-10-03 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="ukma_id",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        100000, message="UKMA ID is a 6-digit value"
                    ),
                    django.core.validators.MaxValueValidator(
                        999999, message="UKMA ID is a 6-digit value"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1991,
                        message="Year cannot be earlier than 1991 (NaUKMA foundation)",
                    ),
                    django.core.validators.MaxValueValidator(
                        9999, message="Year is a 4-digit value"
                    ),
                ]
            ),
        ),
    ]
