# Generated by Django 5.2.7 on 2025-10-21 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speciality",
            options={
                "verbose_name": "Speciality",
                "verbose_name_plural": "Specialities",
            },
        ),
    ]
