# Generated by Django 5.2.7 on 2025-11-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0002_alter_speciality_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="courseoffering",
            name="practice_type",
            field=models.CharField(
                blank=True,
                choices=[("PRACTICE", "Practice"), ("SEMINAR", "Seminar")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="academic_degree",
            field=models.CharField(
                blank=True,
                choices=[("PHD", "PhD"), ("DRSCI", "DoctorOfSciences")],
                default="",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="academic_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASSISTANT", "Assistant"),
                    ("LECTURER", "Lecturer"),
                    ("SENIOR_LECTURER", "SeniorLecturer"),
                    ("ASSOCIATE_PROF", "AssociateProfessor"),
                    ("PROFESSOR", "Professor"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="patronymic",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="student",
            name="patronymic",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
