# Generated by Django 5.2.8 on 2025-11-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0004_alter_student_education_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, db_index=True, default="", max_length=254),
        ),
    ]
