# Generated by Django 5.2.8 on 2025-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0005_add_email_to_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="custom_abbreviation",
            field=models.CharField(
                blank=True,
                help_text="Custom abbreviation for the faculty. If not provided, the name will be used.",
                max_length=255,
                null=True,
            ),
        ),
    ]
