# Generated by Django 5.2.8 on 2025-11-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0006_faculty_custom_abbreviation"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciality",
            name="alias",
            field=models.CharField(
                max_length=255,
                blank=True,
                default="",
                help_text="Custom alias for the speciality. If not provided, the name will be used.",
            ),
        ),
    ]
