# Generated by Django 5.2.8 on 2025-12-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0007_speciality_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="avg_difficulty",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="avg_usefulness",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="ratings_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
