# Generated by Django 5.2.8 on 2025-12-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0008_course_avg_difficulty_course_avg_usefulness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="avg_difficulty",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="course",
            name="avg_usefulness",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="course",
            name="ratings_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
