# Generated by Django 5.2.8 on 2025-12-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0009_alter_course_avg_difficulty_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['ratings_count'], name='course_ratings_count_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['avg_difficulty'], name='course_avg_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['avg_usefulness'], name='course_avg_usefulness_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='course_title_idx'),
        ),
    ]
