# Generated by Django 5.2.8 on 2025-12-21 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0010_add_course_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("UPVOTE", "Upvote"), ("DOWNVOTE", "Downvote")], max_length=10
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_vote",
                        to="rating_app.rating",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_vote",
                        to="rating_app.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "rating")},
            },
        ),
    ]
