# Generated by Django 5.2.8 on 2026-01-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0011_ratingvote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursespeciality',
            options={'verbose_name': 'Course speciality', 'verbose_name_plural': 'Course specialities'},
        ),
        migrations.AlterField(
            model_name='ratingvote',
            name='type',
            field=models.SmallIntegerField(choices=[(-1, 'Downvote'), (1, 'Upvote')]),
        ),
        migrations.AddConstraint(
            model_name='ratingvote',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', [1, -1])), name='rating_vote_type_valid'),
        ),
    ]
