# Generated by Django 5.2.8 on 2026-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0013_courseofferingspeciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseofferingspeciality',
            name='type_kind',
            field=models.CharField(blank=True, choices=[('COMPULSORY', 'Compulsory'), ('ELECTIVE', 'Elective'), ('PROF_ORIENTED', 'ProfOriented')], default=None, max_length=16, null=True),
        ),
    ]
