# Generated by Django 5.2.8 on 2026-03-05 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0014_courseofferingspeciality_type_kind_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="specialities",
        ),
        migrations.DeleteModel(
            name="CourseSpeciality",
        ),
    ]
