# Generated by Django 5.2.8 on 2026-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0014_courseofferingspeciality_type_kind_nullable'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coursespeciality',
            index=models.Index(fields=['speciality', 'type_kind'], name='coursespeciality_spec_type_idx'),
        ),
    ]
