# Generated by Django 5.2.8 on 2026-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0016_student_avatar"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="courseofferingspeciality",
            index=models.Index(
                fields=["speciality", "type_kind"],
                name="cos_spec_type_idx",
            ),
        ),
    ]
