# Generated by Django 5.2.8 on 2026-03-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0018_ratingvote_rating_type_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoffering',
            options={},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['-created_at'], name='rating_created_at_idx'),
        ),
    ]
