# Generated by Django 5.2.12 on 2026-03-08 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0020_course_title_trigram_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='education_level',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='study_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='program_start_academic_year_start',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseOfferingTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weekly_hours', models.PositiveIntegerField()),
                ('lecture_count', models.PositiveIntegerField(blank=True, null=True)),
                ('practice_count', models.PositiveIntegerField(blank=True, null=True)),
                ('practice_type', models.CharField(blank=True, choices=[('PRACTICE', 'Practice'), ('SEMINAR', 'Seminar')], default='', max_length=16)),
                ('exam_type', models.CharField(choices=[('EXAM', 'Exam'), ('CREDIT', 'Credit')], max_length=8)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='rating_app.courseoffering')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offering_terms', to='rating_app.semester')),
            ],
            options={
                'ordering': ['semester__year', 'semester__term'],
                'constraints': [models.CheckConstraint(condition=models.Q(('credits__gt', 0)), name='cot_credits_gt_0'), models.UniqueConstraint(fields=('offering', 'semester'), name='cot_offering_semester_unique')],
            },
        ),
    ]
