# Generated by Django 5.2.12 on 2026-03-08 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0020_course_title_trigram_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='education_level',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='study_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='program_start_academic_year_start',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('code', 'semester'), name='co_code_semester_unique'),
        ),
    ]
