# Generated by Django 5.2.12 on 2026-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0020_course_title_trigram_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseofferingspeciality",
            name="type_kind",
            field=models.CharField(
                choices=[
                    ("COMPULSORY", "Compulsory"),
                    ("ELECTIVE", "Elective"),
                    ("PROF_ORIENTED", "ProfOriented"),
                ],
                max_length=16,
            ),
        ),
    ]
