# Generated by Django 5.2.12 on 2026-03-15 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0021_notification_notificationcursor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationGroupRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("group_key", models.CharField(max_length=255)),
                ("read_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_group_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Group Read",
                "verbose_name_plural": "Notification Group Reads",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "group_key"), name="unique_user_group_read"
                    )
                ],
            },
        ),
    ]
