# Generated by Django 5.2.12 on 2026-03-29 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0022_notification_group_read"),
        ("rating_app", "0023_merge_20260326_2138"),
    ]

    operations = []
