# Generated by Django 5.2.12 on 2026-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0024_merge_20260329_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="instructor",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Temp. free-text field; will be replaced with a verified instructor FK.",
                max_length=30,
            ),
        ),
    ]
