# Generated by Django 5.2.12 on 2026-08-15 13:32

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0028_simplify_instructor_add_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Bold lead-in, e.g. the promoted app's name.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Muted continuation shown next to the title. Hidden on small screens."
                        ),
                        max_length=200,
                    ),
                ),
                (
                    "href",
                    models.URLField(
                        help_text="Where the banner links to. Opens in a new tab.", max_length=500
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        default="Відкрити",
                        help_text="Text of the call-to-action link.",
                        max_length=40,
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        help_text="Square logo. Allowed: svg, png, webp, jpg, jpeg.",
                        upload_to="promo/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["svg", "png", "webp", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "logo_alt",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Alt text for the logo. Falls back to the title when empty.",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only the most recently updated active banner is served.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Promo Banner",
                "verbose_name_plural": "Promo Banners",
                "ordering": ["-updated_at"],
            },
        ),
    ]
