# Generated by Django 5.2.12 on 2026-08-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0029_promobanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promobanner",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Activating this banner deactivates any other active one.",
            ),
        ),
    ]
