# Generated by Django 5.2.12 on 2026-08-15 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0029_rating_instructors_m2m"),
        ("rating_app", "0030_alter_promobanner_is_active"),
    ]

    operations = []
