# Generated by Django 5.2.12 on 2026-09-06 17:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0032_deprecate_rating_instructor"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="course_title_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
