# Generated by Django 5.2.12 on 2026-09-01 23:18

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0032_deprecate_rating_instructor"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(help_text="Shown in Ukrainian, exactly as entered.")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Small tag above the title, e.g. the announcement category.",
                        max_length=40,
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Text of the call-to-action link. Hidden when empty.",
                        max_length=40,
                    ),
                ),
                (
                    "cta_href",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Where the call-to-action links to. Opens in a new tab.",
                        max_length=500,
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Allowed: svg, png, webp, jpg, jpeg.",
                        upload_to="feed/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["svg", "png", "webp", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        choices=[("BRAND", "Brand"), ("INFO", "Info"), ("WARNING", "Warning")],
                        default="BRAND",
                        help_text="Colour treatment of the card.",
                        max_length=16,
                    ),
                ),
                (
                    "pinned",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Pinned posts lead the feed until unpinned.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Places the post in the timeline. A future date schedules it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feed Post",
                "verbose_name_plural": "Feed Posts",
                "ordering": ["-published_at"],
            },
        ),
        migrations.AddIndex(
            model_name="feedpost",
            index=models.Index(fields=["is_active", "-published_at"], name="feed_post_live_idx"),
        ),
    ]
