# Generated by Django 5.2.12 on 2026-09-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0033_feedpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedpost",
            name="accent",
            field=models.CharField(
                choices=[("BRAND", "Brand"), ("INFO", "Info"), ("WARNING", "Warning")],
                default="BRAND",
                help_text="Defines treatment of the card.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="cta_href",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Where the call-to-action links to.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="feedpost",
            name="cta_label",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
