# Generated by Django 5.2.12 on 2026-09-06 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0033_course_title_trgm_idx"),
        ("rating_app", "0034_alter_feedpost_accent_alter_feedpost_body_and_more"),
    ]

    operations = []
