# Generated by Django 5.2.12 on 2026-09-06 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0035_merge_20260906_2001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedpost",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Allowed: png, webp, jpg, jpeg.",
                upload_to="feed/",
                validators=[
                    django.core.validators.FileExtensionValidator(["png", "webp", "jpg", "jpeg"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="promobanner",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Square logo. Allowed: png, webp, jpg, jpeg.",
                upload_to="promo/",
                validators=[
                    django.core.validators.FileExtensionValidator(["png", "webp", "jpg", "jpeg"])
                ],
            ),
        ),
    ]
