# Generated by Django 5.2.12 on 2026-09-08 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0036_alter_feedpost_image_alter_promobanner_logo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="courseoffering",
            name="co_credits_gt_0",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="lecture_count",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="practice_count",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="practice_type",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="weekly_hours",
        ),
    ]
