# Generated by Django 5.2.12 on 2026-09-08 21:35

from django.db import migrations


def build_term_kwargs(offering) -> dict:
    return {
        "offering_id": offering.pk,
        "semester_id": offering.semester_id,
        "credits": offering.credits,
        "weekly_hours": offering.weekly_hours,
        "lecture_count": offering.lecture_count,
        "practice_count": offering.practice_count,
        "practice_type": offering.practice_type,
        "exam_type": offering.exam_type,
    }


def backfill_terms_from_offerings(apps, schema_editor):
    # 0021 created CourseOfferingTerm with no data migration, so offerings
    # predating it have no terms. Copy their per-term fields into one term
    # row each before the offering columns are dropped (#558).
    offering_model = apps.get_model("rating_app", "CourseOffering")
    term_model = apps.get_model("rating_app", "CourseOfferingTerm")

    batch = []
    termless = offering_model.objects.filter(terms__isnull=True).iterator(chunk_size=500)
    for offering in termless:
        batch.append(term_model(**build_term_kwargs(offering)))
        if len(batch) >= 500:
            term_model.objects.bulk_create(batch)
            batch = []
    if batch:
        term_model.objects.bulk_create(batch)


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0036_alter_feedpost_image_alter_promobanner_logo"),
    ]

    operations = [
        migrations.RunPython(
            backfill_terms_from_offerings,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="courseoffering",
            name="co_credits_gt_0",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="lecture_count",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="practice_count",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="practice_type",
        ),
        migrations.RemoveField(
            model_name="courseoffering",
            name="weekly_hours",
        ),
    ]
