# Generated by Django 5.2.12 on 2026-09-11 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _content_type(apps, model):
    ContentType = apps.get_model("contenttypes", "ContentType")
    # `ContentTypeManager` sets `use_in_migrations`, so this is available on the
    # historical model and creates the row when it does not exist yet — which it
    # does not on a fresh database, where `post_migrate` has not run.
    return ContentType.objects.get_for_model(model)


def backfill(apps, schema_editor):
    """Index the rows that predate the table."""
    FeedEvent = apps.get_model("rating_app", "FeedEvent")
    Rating = apps.get_model("rating_app", "Rating")
    FeedPost = apps.get_model("rating_app", "FeedPost")

    rating_type = _content_type(apps, Rating)
    post_type = _content_type(apps, FeedPost)

    reviews = [
        FeedEvent(
            event_type="REVIEW_PUBLISHED",
            occurred_at=created_at,
            is_visible=True,
            pinned=False,
            content_type=rating_type,
            object_id=rating_id,
        )
        for rating_id, created_at in Rating.objects.exclude(comment="").values_list(
            "id", "created_at"
        )
    ]

    posts = [
        FeedEvent(
            event_type="POST_PUBLISHED",
            occurred_at=published_at,
            is_visible=is_active,
            pinned=pinned,
            content_type=post_type,
            object_id=post_id,
        )
        for post_id, published_at, is_active, pinned in FeedPost.objects.values_list(
            "id", "published_at", "is_active", "pinned"
        )
    ]

    # `ignore_conflicts` against `unique_feed_event_source`, so a re-run after a
    # partial failure is a no-op rather than an IntegrityError.
    FeedEvent.objects.bulk_create(reviews + posts, ignore_conflicts=True)


def unbackfill(apps, schema_editor):
    apps.get_model("rating_app", "FeedEvent").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("rating_app", "0036_alter_feedpost_image_alter_promobanner_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("REVIEW_PUBLISHED", "Review Published"),
                            ("POST_PUBLISHED", "Post Published"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        help_text="The source's own timestamp. A future value schedules the item."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("pinned", models.BooleanField(default=False)),
                ("object_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Event",
                "verbose_name_plural": "Feed Events",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_visible", True), ("pinned", False)),
                        fields=["-occurred_at", "-id"],
                        name="feed_event_keyset_idx",
                    ),
                    models.Index(
                        condition=models.Q(("is_visible", True), ("pinned", True)),
                        fields=["-occurred_at", "-id"],
                        name="feed_event_pinned_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"), name="unique_feed_event_source"
                    )
                ],
            },
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
