# Generated by Django 5.2.12 on 2026-09-11 13:44

from django.db import migrations, models

BATCH_SIZE = 1000


def backfill(apps, schema_editor):
    """Index the comments that predate the kind."""
    FeedEvent = apps.get_model("rating_app", "FeedEvent")
    Comment = apps.get_model("rating_app", "Comment")
    ContentType = apps.get_model("contenttypes", "ContentType")
    comment_type = ContentType.objects.get_for_model(Comment)

    events = (
        FeedEvent(
            event_type="COMMENT_PUBLISHED",
            occurred_at=created_at,
            is_visible=True,
            pinned=False,
            content_type=comment_type,
            object_id=comment_id,
        )
        for comment_id, created_at in Comment.objects.values_list("id", "created_at").iterator(
            chunk_size=BATCH_SIZE
        )
    )
    FeedEvent.objects.bulk_create(events, batch_size=BATCH_SIZE, ignore_conflicts=True)


def unbackfill(apps, schema_editor):
    FeedEvent = apps.get_model("rating_app", "FeedEvent")
    FeedEvent.objects.filter(event_type="COMMENT_PUBLISHED").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("rating_app", "0037_feedevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("REVIEW_PUBLISHED", "Review Published"),
                    ("POST_PUBLISHED", "Post Published"),
                    ("COMMENT_PUBLISHED", "Comment Published"),
                ],
                max_length=40,
            ),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
