"""
Application-wide constants.
"""

# PAGINATION
DEFAULT_PAGE_SIZE = 10

MAX_PAGE_SIZE = 100

MIN_PAGE_SIZE = 1

DEFAULT_PAGE_NUMBER = 1  # First page in pagination
MIN_PAGE_NUMBER = DEFAULT_PAGE_NUMBER

# COURSE
DEFAULT_COURSE_PAGE_SIZE = 20

# RATING VALUES
MIN_RATING_VALUE = 1

MAX_RATING_VALUE = 5

# ORDERING
AVG_ORDER_CHOICES = ["asc", "desc"]


# YEARS
MIN_SEMESTER_YEAR = 1991

# COURSE VALUES
MIN_DIFFICULTY_VALUE = 1.0
MAX_DIFFICULTY_VALUE = 5.0
MIN_USEFULNESS_VALUE = 1.0
MAX_USEFULNESS_VALUE = 5.0
