name: Docker Build
on:
  workflow_call:
    inputs:
      profile:
        description: "docker compose profile to use (dev or prod)"
        required: false
        type: string
        default: prod

env:
  SOURCE_CODE_DIR: src

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy default .env file
        working-directory: ${{ env.SOURCE_CODE_DIR }}
        run: |
          cp .env.sample .env

      - name: Build backend image
        working-directory: ${{ env.SOURCE_CODE_DIR }}
        run: docker compose --profile "${{ inputs.profile || 'prod' }}" build backend

      - name: Push backend image
        working-directory: ${{ env.SOURCE_CODE_DIR }}
        run: docker compose --profile "${{ inputs.profile || 'prod' }}" push backend
