---
name: Cleanup Old Container Images

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  cleanup-images:
    name: Cleanup Images
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [rate-ukma/backend, rate-ukma/webapp]
    steps:
      - name: Delete untagged and old tagged versions
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GHCR_PAT }}
          owner: ukma-cs-ssdm-2025
          repository: rate-ukma
          packages: "${{ matrix.package }}"
          keep-n-tagged: 5
          delete-untagged: true
          exclude-tags: latest
          older-than: 14 days
          dry-run: false
