name: Webapp Security Audit

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1" # weekly Monday 07:00 UTC

permissions:
  contents: read
  security-events: write

concurrency:
  group: webapp-security-audit-${{ github.ref }}
  cancel-in-progress: true

env:
  FRONTEND_DIR: src/webapp

jobs:
  security-audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract Node version from package.json
        id: versions
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          NODE_VERSION=$(jq -r '.engines.node' package.json | sed 's/>=//')
          echo "node-version=$NODE_VERSION" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ${{ env.FRONTEND_DIR }}/package.json
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.versions.outputs.node-version }}
          cache: "pnpm"
          cache-dependency-path: ${{ env.FRONTEND_DIR }}/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          pnpm install --frozen-lockfile

      - name: pnpm audit high severity
        working-directory: ${{ env.FRONTEND_DIR }}
        run: pnpm run security:audit

      - name: Snyk test (SARIF upload)
        uses: snyk/actions/node@master
        with:
          command: test
          args: ${{ env.FRONTEND_DIR }} --sarif-file-output=src/webapp/snyk.sarif --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: src/webapp/snyk.sarif
