name: Webapp Security Audit

on:
  push:
    paths:
      - "src/webapp/**"
  pull_request:
    paths:
      - "src/webapp/**"
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1" # weekly Monday 07:00 UTC

permissions:
  contents: read
  security-events: write

env:
  FRONTEND_DIR: src/webapp

jobs:
  security-audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Extract versions from package.json
        id: versions
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          NODE_VERSION=$(jq -r '.engines.node' package.json | sed 's/>=//')
          PNPM_VERSION=$(jq -r '.engines.pnpm' package.json | sed 's/>=//')
          echo "node-version=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "pnpm-version=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Node.js and pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.versions.outputs.node-version }}
          cache: pnpm
          cache-dependency-path: src/webapp/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          corepack enable
          corepack prepare pnpm@${{ steps.versions.outputs.pnpm-version }} --activate
          pnpm install --frozen-lockfile

      - name: pnpm audit high severity
        working-directory: ${{ env.FRONTEND_DIR }}
        run: pnpm run security:audit

      - name: Snyk test (SARIF upload)
        id: snyk
        if: env.SNYK_TOKEN != ''
        uses: snyk/actions/node@master
        with:
          command: test
          args: --severity-threshold=high --sarif-file-output=src/webapp/snyk.sarif
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload SARIF results
        if: steps.snyk.outcome == 'success' && env.SNYK_TOKEN != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.FRONTEND_DIR }}/snyk.sarif
